/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Fachada.SistemaFacade;
import Recursos.GraficaMedicamentos;
import Recursos.GraficaRecetas;
import Recursos.Reporte;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author erick
 */
public class Dg_Estadisticas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_Estadisticas.class.getName());

    /**
     * Creates new form Dg_Estadisticas
     */
    private SistemaFacade sistema;
    public Dg_Estadisticas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Reportes y Estadisticas");  
        setSize(535, 260);           
        setLocationRelativeTo(null);  
        setResizable(false); 
        
        sistema = new SistemaFacade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardEliminaciones = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTotalRecetas2 = new javax.swing.JLabel();
        cardReporte = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cardGrafMedicamentos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotalRecetas3 = new javax.swing.JLabel();
        cardGrafRecetas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTotalRecetas1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cardEliminaciones.setBackground(new java.awt.Color(71, 85, 105));
        cardEliminaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardEliminaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardEliminacionesMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar (1).png"))); // NOI18N

        jLabel14.setForeground(new java.awt.Color(241, 245, 249));
        jLabel14.setText("Visualización");

        lblTotalRecetas2.setForeground(new java.awt.Color(241, 245, 249));
        lblTotalRecetas2.setText("Auditoria Eliminaciones");

        javax.swing.GroupLayout cardEliminacionesLayout = new javax.swing.GroupLayout(cardEliminaciones);
        cardEliminaciones.setLayout(cardEliminacionesLayout);
        cardEliminacionesLayout.setHorizontalGroup(
            cardEliminacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEliminacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardEliminacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalRecetas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardEliminacionesLayout.setVerticalGroup(
            cardEliminacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEliminacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardEliminacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(cardEliminacionesLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalRecetas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cardReporte.setBackground(new java.awt.Color(71, 85, 105));
        cardReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardReporteMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporteReceta.png"))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(241, 245, 249));
        jLabel9.setText("Generar Reporte ");

        jLabel10.setForeground(new java.awt.Color(241, 245, 249));
        jLabel10.setText(" \"Recetas Médicas\"");

        javax.swing.GroupLayout cardReporteLayout = new javax.swing.GroupLayout(cardReporte);
        cardReporte.setLayout(cardReporteLayout);
        cardReporteLayout.setHorizontalGroup(
            cardReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardReporteLayout.setVerticalGroup(
            cardReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(cardReporteLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardGrafMedicamentos.setBackground(new java.awt.Color(71, 85, 105));
        cardGrafMedicamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardGrafMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardGrafMedicamentosMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra-grafica.png"))); // NOI18N

        jLabel16.setForeground(new java.awt.Color(241, 245, 249));
        jLabel16.setText("Generar Gráfica");

        lblTotalRecetas3.setForeground(new java.awt.Color(241, 245, 249));
        lblTotalRecetas3.setText("\"Medicamentos\"");

        javax.swing.GroupLayout cardGrafMedicamentosLayout = new javax.swing.GroupLayout(cardGrafMedicamentos);
        cardGrafMedicamentos.setLayout(cardGrafMedicamentosLayout);
        cardGrafMedicamentosLayout.setHorizontalGroup(
            cardGrafMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGrafMedicamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardGrafMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalRecetas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardGrafMedicamentosLayout.setVerticalGroup(
            cardGrafMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGrafMedicamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardGrafMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(cardGrafMedicamentosLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalRecetas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cardGrafRecetas.setBackground(new java.awt.Color(71, 85, 105));
        cardGrafRecetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardGrafRecetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardGrafRecetasMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lineas.png"))); // NOI18N

        jLabel12.setForeground(new java.awt.Color(241, 245, 249));
        jLabel12.setText("Generar Gráfica");

        lblTotalRecetas1.setForeground(new java.awt.Color(241, 245, 249));
        lblTotalRecetas1.setText("\"Recetas por fecha\"");

        javax.swing.GroupLayout cardGrafRecetasLayout = new javax.swing.GroupLayout(cardGrafRecetas);
        cardGrafRecetas.setLayout(cardGrafRecetasLayout);
        cardGrafRecetasLayout.setHorizontalGroup(
            cardGrafRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGrafRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardGrafRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalRecetas1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardGrafRecetasLayout.setVerticalGroup(
            cardGrafRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGrafRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardGrafRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(cardGrafRecetasLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalRecetas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardEliminaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardGrafMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardGrafRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardGrafMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardEliminaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardGrafRecetas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardEliminacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardEliminacionesMouseClicked
        dispose();
        JFrame parent2 = (JFrame) SwingUtilities.getWindowAncestor(this);
        Dg_VentanaAuditoria dialog = new Dg_VentanaAuditoria(parent2, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_cardEliminacionesMouseClicked

    private void cardReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardReporteMouseClicked
        dispose();
        /*
        Reporte reporte = new Reporte();

        reporte.generarReporteRecetasCompletas();
        */
        sistema.generarReporteRecetas();
    }//GEN-LAST:event_cardReporteMouseClicked

    private void cardGrafMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardGrafMedicamentosMouseClicked
       dispose();
       /*
        GraficaMedicamentos grafica = new GraficaMedicamentos();

        grafica.generarGraficaMedicamentos();
       */
       sistema.generarGraficaMedicamentos();
    }//GEN-LAST:event_cardGrafMedicamentosMouseClicked

    private void cardGrafRecetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardGrafRecetasMouseClicked
        dispose();
        /*
        GraficaRecetas grafica = new GraficaRecetas();

        grafica.generarGraficaRecetasPorFecha();
        */
        sistema.generarGraficaRecetas();
    }//GEN-LAST:event_cardGrafRecetasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dg_Estadisticas dialog = new Dg_Estadisticas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardEliminaciones;
    private javax.swing.JPanel cardGrafMedicamentos;
    private javax.swing.JPanel cardGrafRecetas;
    private javax.swing.JPanel cardReporte;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTotalRecetas1;
    private javax.swing.JLabel lblTotalRecetas2;
    private javax.swing.JLabel lblTotalRecetas3;
    // End of variables declaration//GEN-END:variables
}
