/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Controlador.MedicoController;
import Dao.MedicoDAO;
import Modelo.Medico;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class Dg_MedicosCambios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_MedicosCambios.class.getName());

    /**
     * Creates new form Dg_MedicosCambios
     */
    private String ssnMedico;
    private MedicoController controller;
    public Dg_MedicosCambios(java.awt.Frame parent, boolean modal, String ssnMedico) {
        super(parent, modal);
        initComponents();
        setTitle("Editar Medicos");  
        setSize(350, 450);           
        setLocationRelativeTo(null);  
        setResizable(false); 
        controller = new MedicoController(MedicoDAO.getInstancia());
        
        this.ssnMedico = ssnMedico;
        cargarDatosMedico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaNombreCambios = new javax.swing.JTextField();
        cajaPaternoCambios = new javax.swing.JTextField();
        cbEspecialidadCambios = new javax.swing.JComboBox<>();
        btnEditarMedCambios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cajaMaternoCambios = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spAñosExpCambios = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cajaNombreCambios.setBackground(new java.awt.Color(71, 85, 105));

        cajaPaternoCambios.setBackground(new java.awt.Color(71, 85, 105));

        cbEspecialidadCambios.setBackground(new java.awt.Color(71, 85, 105));
        cbEspecialidadCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Especialidad...", "Cardiología", "Pediatría", "Ginecología", "Medicina General", "Dermatología", "Neurología", "Oncología", "Oftalmología" }));

        btnEditarMedCambios.setBackground(new java.awt.Color(40, 40, 40));
        btnEditarMedCambios.setText("Editar");
        btnEditarMedCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMedCambiosActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(241, 245, 249));
        jLabel3.setText("Nombre:");

        cajaMaternoCambios.setBackground(new java.awt.Color(71, 85, 105));

        jLabel4.setForeground(new java.awt.Color(241, 245, 249));
        jLabel4.setText("Apellido Paterno:");

        jLabel5.setForeground(new java.awt.Color(241, 245, 249));
        jLabel5.setText("Apellido Materno:");

        jLabel6.setForeground(new java.awt.Color(241, 245, 249));
        jLabel6.setText("Especialidad:");

        jLabel7.setForeground(new java.awt.Color(241, 245, 249));
        jLabel7.setText("Años Experiencia:");

        spAñosExpCambios.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarMedCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaPaternoCambios)
                    .addComponent(cajaMaternoCambios)
                    .addComponent(cbEspecialidadCambios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaNombreCambios)
                    .addComponent(spAñosExpCambios))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNombreCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaPaternoCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaMaternoCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEspecialidadCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(spAñosExpCambios))
                .addGap(18, 18, 18)
                .addComponent(btnEditarMedCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarMedCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedCambiosActionPerformed
        
        Medico m = new Medico(
        ssnMedico,
        cajaNombreCambios.getText(),
        cajaPaternoCambios.getText(),
        cajaMaternoCambios.getText(),
        cbEspecialidadCambios.getSelectedItem().toString(),
        Byte.parseByte(spAñosExpCambios.getValue().toString())
);
            

        if (controller.editar(m)) {
            JOptionPane.showMessageDialog(this,"Registro Editado CORRECTAMENTE");
            System.out.println("Registro Editado CORRECTAMENTE");

            limpiarCampos();
            dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Error en la insercion");
            System.out.println("ERROR en la insercion");
        }
    }//GEN-LAST:event_btnEditarMedCambiosActionPerformed

    private void limpiarCampos(){
        
        cajaNombreCambios.setText("");
        cajaPaternoCambios.setText("");
        cajaMaternoCambios.setText("");
        cbEspecialidadCambios.setSelectedIndex(0);
        spAñosExpCambios.setValue(0);
    }
    
    private void cargarDatosMedico(){
        
        ResultSet rs = controller.obtenerMedicoPorSSN(ssnMedico);
        
        try {
            if (rs.next()) {
                
                cajaNombreCambios.setText(rs.getString("nombre"));
                
                cajaPaternoCambios.setText(rs.getString("ape_paterno"));
                
                cajaMaternoCambios.setText(rs.getString("ape_materno"));

                cbEspecialidadCambios.setSelectedItem(rs.getString("especialidad"));

                spAñosExpCambios.setValue((rs.getByte("años_experiencia")));
                
               
            }
        } catch (SQLException e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar datos"
            );
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dg_MedicosCambios dialog = new Dg_MedicosCambios(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarMedCambios;
    private javax.swing.JTextField cajaMaternoCambios;
    private javax.swing.JTextField cajaNombreCambios;
    private javax.swing.JTextField cajaPaternoCambios;
    private javax.swing.JComboBox<String> cbEspecialidadCambios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner spAñosExpCambios;
    // End of variables declaration//GEN-END:variables
}
