/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Controlador.PacienteController;
import Dao.PacienteDAO;
import Modelo.Paciente;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class Dg_PacientesCambios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_PacientesCambios.class.getName());

    /**
     * Creates new form Dg_PacientesCambios
     */
    private String ssnPaciente;
    private PacienteController controller;
    public Dg_PacientesCambios(java.awt.Frame parent, boolean modal, String ssnPaciente) {
        super(parent, modal);
        initComponents();
        setTitle("Editar Recetas");  
        setSize(320, 630);           
        setLocationRelativeTo(null);  
        setResizable(false); 
        controller = new PacienteController(PacienteDAO.getInstancia());
        
        this.ssnPaciente = ssnPaciente;
        cargarMedicosEnCombo();
      
        
        cargarDatosPaciente();
    }
    
    
    private void limpiarCampos(){
        
        
        cajaNombreCambios.setText("");
        cajaApPaternoCambios.setText("");
        cajaApMaternoCambios.setText("");
        spEdadCambios.setValue(0);
        cbSSNMedicoCabCambios.setSelectedIndex(0);
        cajaCalleCambios.setText("");
        cajaNumeroCambios.setText("");
        cajaColoniaCambios.setText("");
        cajaCodPostalCambios.setText("");
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void cargarMedicosEnCombo(){
        cbSSNMedicoCabCambios.removeAllItems();
        
        cbSSNMedicoCabCambios.addItem("Elije Médico...");
        ResultSet rs = controller.obtenerMedicos();
        try {
            while (rs.next()) {
                String ssn = rs.getString("SSN");

                cbSSNMedicoCabCambios.addItem(ssn);

            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar médicos");
        }
        
    }
    
    private void actualizarLabelMedico(){
        
        if (cbSSNMedicoCabCambios.getSelectedIndex() == 0) return; 
        String ssn = cbSSNMedicoCabCambios.getSelectedItem().toString();
        String nombre = controller.obtenerNombreCompleto(ssn);
        lblNombreMedico.setText("Médico asig. " + nombre);
    }
    

    private void cargarDatosPaciente() {

        ResultSet rs = controller.obtenerPacientePorSSN(ssnPaciente);

        try {

            if (rs.next()) {
                
                cajaNombreCambios.setText(rs.getString("nombre"));
                
                cajaApPaternoCambios.setText(rs.getString("ape_paterno"));
                
                cajaApMaternoCambios.setText(rs.getString("ape_materno"));
                
                spEdadCambios.setValue(rs.getInt("edad"));

                cbSSNMedicoCabCambios.setSelectedItem(rs.getString("ssn_medico_cabecera"));

                cajaCalleCambios.setText(rs.getString("calle"));
                
                cajaNumeroCambios.setText(rs.getString("numero"));

                cajaColoniaCambios.setText(rs.getString("colonia"));

                cajaCodPostalCambios.setText(rs.getString("codigo_postal"));

                actualizarLabelMedico();
               
            }

        } catch (SQLException e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar datos"
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        cajaColoniaCambios = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cajaCodPostalCambios = new javax.swing.JTextField();
        btnEditarPacientes = new javax.swing.JButton();
        cajaNombreCambios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cajaApPaternoCambios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaApMaternoCambios = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spEdadCambios = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cbSSNMedicoCabCambios = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cajaCalleCambios = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaNumeroCambios = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setForeground(new java.awt.Color(241, 245, 249));
        jLabel9.setText("Colonia:");

        cajaColoniaCambios.setBackground(new java.awt.Color(71, 85, 105));

        jLabel10.setForeground(new java.awt.Color(241, 245, 249));
        jLabel10.setText("Código Postal:");

        cajaCodPostalCambios.setBackground(new java.awt.Color(71, 85, 105));

        btnEditarPacientes.setBackground(new java.awt.Color(40, 40, 40));
        btnEditarPacientes.setForeground(new java.awt.Color(241, 245, 249));
        btnEditarPacientes.setText("EDITAR");
        btnEditarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacientesActionPerformed(evt);
            }
        });

        cajaNombreCambios.setBackground(new java.awt.Color(71, 85, 105));

        jLabel2.setForeground(new java.awt.Color(241, 245, 249));
        jLabel2.setText("Nombre:");

        cajaApPaternoCambios.setBackground(new java.awt.Color(71, 85, 105));

        jLabel3.setForeground(new java.awt.Color(241, 245, 249));
        jLabel3.setText("Apellido Paterno:");

        cajaApMaternoCambios.setBackground(new java.awt.Color(71, 85, 105));

        jLabel4.setForeground(new java.awt.Color(241, 245, 249));
        jLabel4.setText("Apellido Materno:");

        jLabel5.setForeground(new java.awt.Color(241, 245, 249));
        jLabel5.setText("Edad:");

        cbSSNMedicoCabCambios.setBackground(new java.awt.Color(71, 85, 105));
        cbSSNMedicoCabCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSNMedicoCabCambiosActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(241, 245, 249));
        jLabel6.setText("SSN Medico Cab.");

        lblNombreMedico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNombreMedico.setForeground(new java.awt.Color(241, 245, 249));
        lblNombreMedico.setText("jLabel11");

        jLabel7.setForeground(new java.awt.Color(241, 245, 249));
        jLabel7.setText("Calle:");

        cajaCalleCambios.setBackground(new java.awt.Color(71, 85, 105));

        jLabel8.setForeground(new java.awt.Color(241, 245, 249));
        jLabel8.setText("Número:");

        cajaNumeroCambios.setBackground(new java.awt.Color(71, 85, 105));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cajaCalleCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cajaNumeroCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cajaColoniaCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cajaCodPostalCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbSSNMedicoCabCambios, 0, 140, Short.MAX_VALUE)
                                        .addComponent(cajaApMaternoCambios)
                                        .addComponent(cajaApPaternoCambios)
                                        .addComponent(cajaNombreCambios)
                                        .addComponent(spEdadCambios)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addGap(27, 27, 27))
                                .addComponent(lblNombreMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNombreCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaApPaternoCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaApMaternoCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spEdadCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSSNMedicoCabCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaCalleCambios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNumeroCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaColoniaCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCodPostalCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacientesActionPerformed

        Paciente p = new Paciente(ssnPaciente,
            cajaNombreCambios.getText(),
            cajaApPaternoCambios.getText(),
            cajaApMaternoCambios.getText(),
            Byte.parseByte(spEdadCambios.getValue().toString()),
            cbSSNMedicoCabCambios.getSelectedItem().toString(),
            cajaCalleCambios.getText(),
            cajaNumeroCambios.getText(),
            cajaColoniaCambios.getText(),
            Integer.parseInt(cajaCodPostalCambios.getText()));

        if (controller.editar(p)) {
            JOptionPane.showMessageDialog(this,"Registro Editado CORRECTAMENTE");
            System.out.println("Registro Editado CORRECTAMENTE");

            limpiarCampos();
            dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Error en la insercion");
            System.out.println("ERROR en la insercion");
        }
    }//GEN-LAST:event_btnEditarPacientesActionPerformed

    private void cbSSNMedicoCabCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSNMedicoCabCambiosActionPerformed
        actualizarLabelMedico();
    }//GEN-LAST:event_cbSSNMedicoCabCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dg_PacientesCambios dialog = new Dg_PacientesCambios(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPacientes;
    private javax.swing.JTextField cajaApMaternoCambios;
    private javax.swing.JTextField cajaApPaternoCambios;
    private javax.swing.JTextField cajaCalleCambios;
    private javax.swing.JTextField cajaCodPostalCambios;
    private javax.swing.JTextField cajaColoniaCambios;
    private javax.swing.JTextField cajaNombreCambios;
    private javax.swing.JTextField cajaNumeroCambios;
    private javax.swing.JComboBox<String> cbSSNMedicoCabCambios;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JSpinner spEdadCambios;
    // End of variables declaration//GEN-END:variables
}
