/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Controlador.RecetaController;
import Dao.RecetaDAO;
import Modelo.Receta;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author erick
 */
public class Dg_RecetasAltas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_RecetasAltas.class.getName());

    /**
     * Creates new form Dg_RecetasAltas
     */
    private RecetaController controller;
    public Dg_RecetasAltas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Agregar Recetas");  
        setSize(320, 630);           
        setLocationRelativeTo(null);  
        setResizable(false); 
        controller = new RecetaController(RecetaDAO.getInstancia());
        cargarMedicosEnCombo();
        cargarPacientesEnCombo();
        
        
        try {
        MaskFormatter formatoFecha = new MaskFormatter("##/##/####");
        formatoFecha.setPlaceholderCharacter('_');

        cajaFechaAltas.setFormatterFactory(
            new DefaultFormatterFactory(formatoFecha)
        );

        } catch (ParseException e) {
            e.printStackTrace();
        }
    
    }
    
    private void limpiarCampos(){
        
        cbSSNMedicoAltas.setSelectedIndex(0);
        cbSSNPacienteAltas.setSelectedIndex(0);
        cajaMedicamentoAltas.setText("");
        cajaFechaAltas.setText("");
        cajaCantidadAltas.setText("");
        cbUnidadAltas.setSelectedIndex(0);
        cajaIndicacionesAltas.setText("");
    }
    
    private void cargarMedicosEnCombo(){
        cbSSNMedicoAltas.removeAllItems();
        
        cbSSNMedicoAltas.addItem("Elije Médico...");
        ResultSet rs = controller.obtenerMedicos();
        try {
            while (rs.next()) {
                String ssn = rs.getString("SSN");

                cbSSNMedicoAltas.addItem(ssn);

            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar médicos");
        }
        
    }
    
    private void actualizarLabelMedico(){
        
        if (cbSSNMedicoAltas.getSelectedItem() == null) return;
        String ssn = cbSSNMedicoAltas.getSelectedItem().toString();
        String nombre = controller.obtenerNombreCompletoMedico(ssn);
        lblMedico.setText("Médico asig. " + nombre);
    }
    
    private void cargarPacientesEnCombo(){
        cbSSNPacienteAltas.removeAllItems();
        
        cbSSNPacienteAltas.addItem("Elije Paciente...");
        ResultSet rs = controller.obtenerPacientes();
        try {
            while (rs.next()) {
                String ssn = rs.getString("SSN");

                cbSSNPacienteAltas.addItem(ssn);

            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar médicos");
        }
        
    }
    
    private void actualizarLabelPaciente(){
        
        if (cbSSNPacienteAltas.getSelectedItem() == null) return;
        String ssn = cbSSNPacienteAltas.getSelectedItem().toString();
        String nombre = controller.obtenerNombreCompletoPaciente(ssn);
        lblPaciente.setText("Paciente asig. " + nombre);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajaIndicacionesAltas = new javax.swing.JTextField();
        btnAgregarRecetas = new javax.swing.JButton();
        cbSSNMedicoAltas = new javax.swing.JComboBox<>();
        cbSSNPacienteAltas = new javax.swing.JComboBox<>();
        cajaMedicamentoAltas = new javax.swing.JTextField();
        cajaCantidadAltas = new javax.swing.JTextField();
        lblMedico = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        cajaFechaAltas = new javax.swing.JFormattedTextField();
        cbUnidadAltas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setForeground(new java.awt.Color(241, 245, 249));
        jLabel2.setText("SSN_Medico:");

        jLabel3.setForeground(new java.awt.Color(241, 245, 249));
        jLabel3.setText("SSN_Paciente:");

        jLabel4.setForeground(new java.awt.Color(241, 245, 249));
        jLabel4.setText("Medicamento:");

        jLabel5.setForeground(new java.awt.Color(241, 245, 249));
        jLabel5.setText("Fecha:");

        jLabel6.setForeground(new java.awt.Color(241, 245, 249));
        jLabel6.setText("Cantidad:");

        jLabel7.setForeground(new java.awt.Color(241, 245, 249));
        jLabel7.setText("Unidad:");

        jLabel8.setForeground(new java.awt.Color(241, 245, 249));
        jLabel8.setText("Indicaciones:");

        cajaIndicacionesAltas.setBackground(new java.awt.Color(71, 85, 105));

        btnAgregarRecetas.setBackground(new java.awt.Color(40, 40, 40));
        btnAgregarRecetas.setText("AGREGAR");
        btnAgregarRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRecetasActionPerformed(evt);
            }
        });

        cbSSNMedicoAltas.setBackground(new java.awt.Color(71, 85, 105));
        cbSSNMedicoAltas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSSNMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSNMedicoAltasActionPerformed(evt);
            }
        });

        cbSSNPacienteAltas.setBackground(new java.awt.Color(71, 85, 105));
        cbSSNPacienteAltas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSSNPacienteAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSNPacienteAltasActionPerformed(evt);
            }
        });

        cajaMedicamentoAltas.setBackground(new java.awt.Color(71, 85, 105));

        cajaCantidadAltas.setBackground(new java.awt.Color(71, 85, 105));

        lblMedico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMedico.setForeground(new java.awt.Color(241, 245, 249));
        lblMedico.setText("jLabel9");

        lblPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPaciente.setForeground(new java.awt.Color(241, 245, 249));
        lblPaciente.setText("jLabel11");

        cajaFechaAltas.setBackground(new java.awt.Color(71, 85, 105));

        cbUnidadAltas.setBackground(new java.awt.Color(71, 85, 105));
        cbUnidadAltas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije Unidad...", "mg", "g", "mcg", "ml", "tabletas", "cápsulas", "gotas", "ampolletas" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaCantidadAltas, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(cajaFechaAltas)
                            .addComponent(cbUnidadAltas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSSNPacienteAltas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajaMedicamentoAltas)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAgregarRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cajaIndicacionesAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbSSNMedicoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSSNMedicoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSSNPacienteAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMedicamentoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cajaFechaAltas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaCantidadAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cbUnidadAltas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cajaIndicacionesAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRecetasActionPerformed
       String fechaTexto = cajaFechaAltas.getText();

        if (fechaTexto.contains("_")) {
            JOptionPane.showMessageDialog(null, "Completa la fecha");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);

        try {
            Date fecha = sdf.parse(fechaTexto);
            LocalDate fechaLocal = fecha.toInstant()
            .atZone(java.time.ZoneId.systemDefault())
            .toLocalDate();
            //java.sql.Date fechaBD = new java.sql.Date(fecha.getTime());

            System.out.println("Fecha lista para BD: " + fechaLocal);
            
            
            Receta r = new Receta(cbSSNMedicoAltas.getSelectedItem().toString(), 
                    cbSSNPacienteAltas.getSelectedItem().toString(), 
                    cajaMedicamentoAltas.getText(), 
                    fechaLocal, 
                    Integer.parseInt(cajaCantidadAltas.getText()), 
                    cbUnidadAltas.getSelectedItem().toString(), 
                    cajaIndicacionesAltas.getText());
            
            if (controller.agregar(r)) {
                JOptionPane.showMessageDialog(this,"Registro Agregado CORRECTAMENTE");
                System.out.println("Registro Agregado CORRECTAMENTE");
                
                
                limpiarCampos();   
                dispose(); 
            }else{
                    JOptionPane.showMessageDialog(this,"Error en la insercion");
                    System.out.println("ERROR en la insercion");
                 }
            
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fecha inválida");
        }
    }//GEN-LAST:event_btnAgregarRecetasActionPerformed

    private void cbSSNMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSNMedicoAltasActionPerformed
        actualizarLabelMedico();
    }//GEN-LAST:event_cbSSNMedicoAltasActionPerformed

    private void cbSSNPacienteAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSNPacienteAltasActionPerformed
        actualizarLabelPaciente();
    }//GEN-LAST:event_cbSSNPacienteAltasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dg_RecetasAltas dialog = new Dg_RecetasAltas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRecetas;
    private javax.swing.JTextField cajaCantidadAltas;
    private javax.swing.JFormattedTextField cajaFechaAltas;
    private javax.swing.JTextField cajaIndicacionesAltas;
    private javax.swing.JTextField cajaMedicamentoAltas;
    private javax.swing.JComboBox<String> cbSSNMedicoAltas;
    private javax.swing.JComboBox<String> cbSSNPacienteAltas;
    private javax.swing.JComboBox<String> cbUnidadAltas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblPaciente;
    // End of variables declaration//GEN-END:variables
}
