/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Controlador.MedicoController;
import Controlador.PacienteController;
import Controlador.RecetaController;
import Dao.MedicoDAO;
import Dao.PacienteDAO;
import Dao.RecetaDAO;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author erick
 */
public class VentanaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPrincipal
     */
    private MedicoController medicoController;
    private PacienteController pacienteController;
    private RecetaController recetaController;
    public VentanaPrincipal() {
        initComponents();
        
        medicoController = new MedicoController(MedicoDAO.getInstancia());

        pacienteController = new PacienteController(PacienteDAO.getInstancia());

        recetaController = new RecetaController(RecetaDAO.getInstancia());
        
        cargarEstadisticas();
        
    }
    
    public void cargarEstadisticas() {

        lblTotalMedicos.setText(
                String.valueOf(
                        medicoController.obtenerTotalMedicos()
                )
        );

        lblTotalPacientes.setText(
                String.valueOf(
                        pacienteController.obtenerTotalPacientes()
                )
        );

        lblTotalRecetas.setText(
                String.valueOf(
                        recetaController.obtenerTotalRecetas()
                )
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cardMedicamentos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalMedicos = new javax.swing.JLabel();
        cardMedicamentos1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalPacientes = new javax.swing.JLabel();
        cardMedicamentos2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTotalRecetas = new javax.swing.JLabel();
        cardMedicamentos4 = new javax.swing.JPanel();
        lblClic = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(46, 61, 84));
        setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 245, 249));
        jLabel1.setText("Visualización y administración de información clínica.");

        jPanel2.setBackground(new java.awt.Color(30, 41, 59));

        cardMedicamentos.setBackground(new java.awt.Color(71, 85, 105));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 245, 249));
        jLabel3.setText("Médicos Registrados");

        lblTotalMedicos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalMedicos.setForeground(new java.awt.Color(241, 245, 249));
        lblTotalMedicos.setText("jLabel8");

        javax.swing.GroupLayout cardMedicamentosLayout = new javax.swing.GroupLayout(cardMedicamentos);
        cardMedicamentos.setLayout(cardMedicamentosLayout);
        cardMedicamentosLayout.setHorizontalGroup(
            cardMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addComponent(lblTotalMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cardMedicamentosLayout.setVerticalGroup(
            cardMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentosLayout.createSequentialGroup()
                .addGroup(cardMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardMedicamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(cardMedicamentosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(cardMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalMedicos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardMedicamentos1.setBackground(new java.awt.Color(71, 85, 105));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/examen (1).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 245, 249));
        jLabel5.setText("Pacientes Registrados");

        lblTotalPacientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalPacientes.setForeground(new java.awt.Color(241, 245, 249));
        lblTotalPacientes.setText("jLabel8");

        javax.swing.GroupLayout cardMedicamentos1Layout = new javax.swing.GroupLayout(cardMedicamentos1);
        cardMedicamentos1.setLayout(cardMedicamentos1Layout);
        cardMedicamentos1Layout.setHorizontalGroup(
            cardMedicamentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cardMedicamentos1Layout.setVerticalGroup(
            cardMedicamentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMedicamentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardMedicamentos1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(cardMedicamentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardMedicamentos2.setBackground(new java.awt.Color(71, 85, 105));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receta.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(241, 245, 249));
        jLabel7.setText("Recetas emitidas");

        lblTotalRecetas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalRecetas.setForeground(new java.awt.Color(241, 245, 249));
        lblTotalRecetas.setText("jLabel8");

        javax.swing.GroupLayout cardMedicamentos2Layout = new javax.swing.GroupLayout(cardMedicamentos2);
        cardMedicamentos2.setLayout(cardMedicamentos2Layout);
        cardMedicamentos2Layout.setHorizontalGroup(
            cardMedicamentos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentos2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cardMedicamentos2Layout.setVerticalGroup(
            cardMedicamentos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMedicamentos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardMedicamentos2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(cardMedicamentos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalRecetas)))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardMedicamentos4.setBackground(new java.awt.Color(71, 85, 105));
        cardMedicamentos4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardMedicamentos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardMedicamentos4MouseClicked(evt);
            }
        });

        lblClic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estadisticas.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(241, 245, 249));
        jLabel14.setText("Clic para ir a \"Reportes y Estadisticas\"");

        javax.swing.GroupLayout cardMedicamentos4Layout = new javax.swing.GroupLayout(cardMedicamentos4);
        cardMedicamentos4.setLayout(cardMedicamentos4Layout);
        cardMedicamentos4Layout.setHorizontalGroup(
            cardMedicamentos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentos4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardMedicamentos4Layout.setVerticalGroup(
            cardMedicamentos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMedicamentos4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMedicamentos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardMedicamentos4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblClic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardMedicamentos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardMedicamentos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardMedicamentos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cardMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardMedicamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardMedicamentos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardMedicamentos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void cardMedicamentos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMedicamentos4MouseClicked
        JFrame parent2 = (JFrame) SwingUtilities.getWindowAncestor(this);
        Dg_Estadisticas dialog = new Dg_Estadisticas(parent2, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_cardMedicamentos4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardMedicamentos;
    private javax.swing.JPanel cardMedicamentos1;
    private javax.swing.JPanel cardMedicamentos2;
    private javax.swing.JPanel cardMedicamentos4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClic;
    private javax.swing.JLabel lblTotalMedicos;
    private javax.swing.JLabel lblTotalPacientes;
    private javax.swing.JLabel lblTotalRecetas;
    // End of variables declaration//GEN-END:variables
}
