/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Controlador.MedicoDAO;
import Modelo.ResultSetTableModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author erick
 */

public class VentanaMedicos extends javax.swing.JPanel {

    /**
     * Creates new form VentanaMedicos
     */
    private Timer timerBusqueda;
    MedicoDAO medicoDAO = MedicoDAO.getInstancia();
    public VentanaMedicos() {
        initComponents();
        
        
        cajaSSNMedicos.setEditable(false);
        cajaNombreMedicos.setEnabled(false);
        cajaApPaternoMedicos.setEnabled(false);
        cajaApMaternoMedicos.setEnabled(false);
        cbEspecialidadMedicos.setEnabled(false);
        cajaExperienciaMedicos.setEnabled(false);
        btnEliminarMedicos.setEnabled(false);
        btnEditarMedicos.setEnabled(false);
        
        medicoDAO.actualizarTabla(tablaRegMedicos);
        
        timerBusqueda = new Timer(300, e -> {
        String texto = cajaBusqueda.getText();

        ResultSetTableModel modelo = medicoDAO.obtenerMedicosFiltrados(texto);
        tablaRegMedicos.setModel(modelo);
    });
    timerBusqueda.setRepeats(false);
    
    
    //Selecion de tabla para llenar campos
    tablaRegMedicos.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting()) {
        int fila = tablaRegMedicos.getSelectedRow();

        if (fila != -1) {
            cajaSSNMedicos.setText(tablaRegMedicos.getValueAt(fila, 0).toString());
            cajaNombreMedicos.setText(tablaRegMedicos.getValueAt(fila, 1).toString());
            cajaApPaternoMedicos.setText(tablaRegMedicos.getValueAt(fila, 2).toString());
            cajaApMaternoMedicos.setText(tablaRegMedicos.getValueAt(fila, 3).toString());
            cbEspecialidadMedicos.setSelectedItem(tablaRegMedicos.getValueAt(fila, 4).toString());
            cajaExperienciaMedicos.setText(tablaRegMedicos.getValueAt(fila, 5).toString());
            
            btnEliminarMedicos.setEnabled(true);
            btnEditarMedicos.setEnabled(true);
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaSSNMedicos = new javax.swing.JTextField();
        cajaNombreMedicos = new javax.swing.JTextField();
        cajaApPaternoMedicos = new javax.swing.JTextField();
        cajaApMaternoMedicos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cajaExperienciaMedicos = new javax.swing.JTextField();
        btnAgregarMedicos = new javax.swing.JButton();
        btnEliminarMedicos = new javax.swing.JButton();
        btnEditarMedicos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegMedicos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cajaBusqueda = new javax.swing.JTextField();
        cbEspecialidadMedicos = new javax.swing.JComboBox<>();
        btnLimpiarCampos = new javax.swing.JButton();

        setBackground(new java.awt.Color(46, 61, 84));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 245, 249));
        jLabel1.setText("SSN:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 245, 249));
        jLabel2.setText("Ap. Materno:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 245, 249));
        jLabel4.setText("Ap. Paterno:");

        cajaSSNMedicos.setBackground(new java.awt.Color(71, 85, 105));

        cajaNombreMedicos.setBackground(new java.awt.Color(71, 85, 105));
        cajaNombreMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreMedicosActionPerformed(evt);
            }
        });

        cajaApPaternoMedicos.setBackground(new java.awt.Color(71, 85, 105));

        cajaApMaternoMedicos.setBackground(new java.awt.Color(71, 85, 105));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 245, 249));
        jLabel5.setText("Especialidad:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 245, 249));
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(241, 245, 249));
        jLabel7.setText("Años Experiencia:");

        cajaExperienciaMedicos.setBackground(new java.awt.Color(71, 85, 105));

        btnAgregarMedicos.setBackground(new java.awt.Color(40, 40, 40));
        btnAgregarMedicos.setForeground(new java.awt.Color(241, 245, 249));
        btnAgregarMedicos.setText("NUEVO");
        btnAgregarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedicosActionPerformed(evt);
            }
        });

        btnEliminarMedicos.setBackground(new java.awt.Color(40, 40, 40));
        btnEliminarMedicos.setForeground(new java.awt.Color(241, 245, 249));
        btnEliminarMedicos.setText("ELIMINAR");
        btnEliminarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMedicosActionPerformed(evt);
            }
        });

        btnEditarMedicos.setBackground(new java.awt.Color(40, 40, 40));
        btnEditarMedicos.setForeground(new java.awt.Color(241, 245, 249));
        btnEditarMedicos.setText("EDITAR");

        jScrollPane1.setBackground(new java.awt.Color(241, 245, 249));
        jScrollPane1.setForeground(new java.awt.Color(71, 85, 105));

        tablaRegMedicos.setBackground(new java.awt.Color(71, 85, 105));
        tablaRegMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SSN", "Nombre", "Apellido Paterno", "Apellido Materno", "Especialidad", "Años Experiencia"
            }
        ));
        jScrollPane1.setViewportView(tablaRegMedicos);

        jLabel3.setText("Buscar");

        cajaBusqueda.setBackground(new java.awt.Color(71, 85, 105));
        cajaBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaBusquedaKeyReleased(evt);
            }
        });

        cbEspecialidadMedicos.setBackground(new java.awt.Color(71, 85, 105));
        cbEspecialidadMedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Especialidad...", "Cardiología", "Pediatría", "Ginecología", "Medicina General", "Dermatología", "Neurología", "Oncología", "Oftalmología" }));

        btnLimpiarCampos.setBackground(new java.awt.Color(40, 40, 40));
        btnLimpiarCampos.setText("LIMPIAR");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cajaApMaternoMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbEspecialidadMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cajaSSNMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cajaNombreMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaApPaternoMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaExperienciaMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaSSNMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNombreMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaApPaternoMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaApMaternoMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaExperienciaMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEspecialidadMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void limpiarCampos(){
        cajaSSNMedicos.setText("");
        cajaNombreMedicos.setText("");
        cajaApPaternoMedicos.setText("");
        cajaApMaternoMedicos.setText("");
        cbEspecialidadMedicos.setSelectedIndex(0);
        cajaExperienciaMedicos.setText("");
        cajaBusqueda.setText("");
        btnEliminarMedicos.setEnabled(false);
        btnEditarMedicos.setEnabled(false);
    }
    
    public void habilitarCamposEdicion(boolean habilitar){
        cajaSSNMedicos.setEditable(habilitar);
        cajaNombreMedicos.setEnabled(habilitar);
        cajaApPaternoMedicos.setEnabled(habilitar);
        cajaApMaternoMedicos.setEnabled(habilitar);
        cbEspecialidadMedicos.setEnabled(habilitar);
        cajaExperienciaMedicos.setEnabled(habilitar);
        btnEditarMedicos.setEnabled(habilitar);
    }
    
    private void cajaNombreMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreMedicosActionPerformed
    
    private void btnAgregarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicosActionPerformed
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        Dg_MedicosAltas dialog = new Dg_MedicosAltas(parent, true, tablaRegMedicos); // modal
        dialog.setVisible(true);
        medicoDAO.actualizarTabla(tablaRegMedicos);
    }//GEN-LAST:event_btnAgregarMedicosActionPerformed

    private void cajaBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaBusquedaKeyReleased
        timerBusqueda.restart();
    }//GEN-LAST:event_cajaBusquedaKeyReleased

    private void btnEliminarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMedicosActionPerformed
        
        if (medicoDAO.eliminarMedico(cajaSSNMedicos.getText())){

                medicoDAO.actualizarTabla(tablaRegMedicos);
                JOptionPane.showMessageDialog(this, "Registro eliminado correctamente");
                
                limpiarCampos();
            }else {
                JOptionPane.showMessageDialog(this, "ERROR al eliminar el registro",
                "No existe ese SSN", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEliminarMedicosActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicos;
    private javax.swing.JButton btnEditarMedicos;
    private javax.swing.JButton btnEliminarMedicos;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JTextField cajaApMaternoMedicos;
    private javax.swing.JTextField cajaApPaternoMedicos;
    private javax.swing.JTextField cajaBusqueda;
    private javax.swing.JTextField cajaExperienciaMedicos;
    private javax.swing.JTextField cajaNombreMedicos;
    private javax.swing.JTextField cajaSSNMedicos;
    private javax.swing.JComboBox<String> cbEspecialidadMedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegMedicos;
    // End of variables declaration//GEN-END:variables
}
